version: '3'

services:
  plone:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./data/filestorage:/opt/plone/zeocluster/var/filestorage
      - ./data/blobstorage:/opt/plone/zeocluster/var/blobstorage
    restart: always
